version: '3.11.1'

services:
  web:
    build:
      context: .
    container_name: "tkti_web"
    restart: always
    command: bash ./entrypoint.sh
    volumes:
      - .:/usr/src/app
      - media_volume:/var/www/tkti_uz/media
      - ./static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    networks:
      - my_network

networks:
  my_network:

volumes:
  media_volume:
