from .news import *
from .posts import *
from .widgets import *
from main.models.partners import *
from main.models.tkti_shop import *
from main.models.departments import *
from main.models.sertificates import *
from main.models.sections_and_centers import *
from main.models.department_administrations import *
