# Generated by Django 4.2.5 on 2024-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ads_pdf_file_en_ads_pdf_file_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brmitems',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/brm_items/%d'),
        ),
        migrations.AddField(
            model_name='brmitems',
            name='pdf_file_en',
            field=models.FileField(blank=True, null=True, upload_to='pdf/en/brm_items/%d'),
        ),
        migrations.AddField(
            model_name='brmitems',
            name='pdf_file_ru',
            field=models.FileField(blank=True, null=True, upload_to='pdf/ru/brm_items/%d'),
        ),
        migrations.AddField(
            model_name='brmitems',
            name='video_file',
            field=models.FileField(blank=True, help_text="agar video fayl mavjud bo'lsa yuklang.", null=True, upload_to='videos/brm_items/%d/', verbose_name='Video fayl'),
        ),
    ]
