# Generated by Django 4.2.5 on 2024-03-18 00:04

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_basevariables_positions_topnavbar_extrafile_brm_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studydegrees',
            options={'managed': True, 'ordering': ('order_num',), 'verbose_name': "Ta'lim darajalari", 'verbose_name_plural': "Ta'lim darajalari"},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'managed': True, 'ordering': ('order_num',), 'verbose_name': "Bo'lim va Markazlar xodimlari", 'verbose_name_plural': "Bo'lim va Markazlar xodimlari"},
        ),
        migrations.AddField(
            model_name='learningway',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_area_faculty', to='main.posts', verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='studydegrees',
            name='order_num',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqam'),
        ),
        migrations.AddField(
            model_name='workers',
            name='order_num',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqam'),
        ),
        migrations.AlterField(
            model_name='educationalareas',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Faqat *.pdf formatdagi faylarni yuklang', max_length=255, null=True, upload_to='pdf/educational_areas/%Y-%m-%d/', verbose_name='PDF fayl'),
        ),
        migrations.CreateModel(
            name='ThemesForEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mavzu nomi')),
                ('name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mavzu nomi')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mavzu nomi')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mavzu nomi')),
                ('desc', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Haqida')),
                ('desc_uz', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Haqida')),
                ('desc_ru', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Haqida')),
                ('desc_en', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Haqida')),
                ('teacher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy raxbar')),
                ('teacher_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy raxbar')),
                ('teacher_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy raxbar')),
                ('teacher_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy raxbar')),
                ('finance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Moliyalashtiruvi')),
                ('finance_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Moliyalashtiruvi')),
                ('finance_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Moliyalashtiruvi')),
                ('finance_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Moliyalashtiruvi')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('education_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_areas_themes', to='main.educationalareas')),
            ],
            options={
                'verbose_name': 'DSc va PHD Mavzulari',
                'verbose_name_plural': 'DSc va PHD Mavzulari',
                'db_table': 'themes_for_education',
                'ordering': ('added_at',),
            },
        ),
        migrations.CreateModel(
            name='EntryRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('day', 'Kundizgi'), ('evening', 'Kechki'), ('externally', 'Sirtqi')], max_length=100, null=True)),
                ('requirement', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Kirish talablari')),
                ('requirement_uz', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Kirish talablari')),
                ('requirement_ru', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Kirish talablari')),
                ('requirement_en', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Kirish talablari')),
                ('full_time_fee', models.IntegerField(default=0, verbose_name='Kantrakt miqdori')),
                ('dept_fee', models.IntegerField(default=0, verbose_name='Kredit miqdori')),
                ('education_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_area_requirements', to='main.educationalareas')),
            ],
            options={
                'verbose_name': 'Kirish talablari',
                'verbose_name_plural': 'Kirish talablari',
                'db_table': 'entry_requirements',
                'ordering': ('education_area',),
            },
        ),
        migrations.CreateModel(
            name='AboutStudyProgramPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('day', 'Kundizgi'), ('evening', 'Kechki'), ('externally', 'Sirtqi')], max_length=100, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Faqat *.pdf formatdagi faylarni yuklang', max_length=255, null=True, upload_to='pdf/about_study_program_pdf/%Y/%m/%d/', verbose_name='PDF fayl')),
                ('pdf_file_en', models.FileField(blank=True, help_text='Faqat *.pdf formatdagi faylarni yuklang', max_length=255, null=True, upload_to='pdf/en/about_study_program_pdf/%Y/%m/%d/', verbose_name='EN PDF fayl')),
                ('pdf_file_ru', models.FileField(blank=True, help_text='Faqat *.pdf formatdagi faylarni yuklang', max_length=255, null=True, upload_to='pdf/ru/about_study_program_pdf/%Y/%m/%d/', verbose_name='RU PDF fayl')),
                ('education_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_area', to='main.educationalareas')),
            ],
            options={
                'verbose_name': "Ta'lim yo'nalishlari xaqidagi pdf",
                'verbose_name_plural': "Ta'lim yo'nalishlari xaqidagi pdf",
                'db_table': 'about_study_program_pdf',
                'ordering': ('education_area',),
            },
        ),
    ]
