# Generated by Django 4.2.5 on 2024-03-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_studydegrees_options_alter_workers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstudyprogrampdf',
            name='type',
            field=models.CharField(blank=True, choices=[('day', 'Kundizgi'), ('evening', 'Kechki'), ('externally', 'Sirtqi'), ('master', 'Magistratura'), ('phd', 'PHD'), ('dsc', 'DSc')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entryrequirements',
            name='type',
            field=models.CharField(blank=True, choices=[('day', 'Kundizgi'), ('evening', 'Kechki'), ('externally', 'Sirtqi'), ('master', 'Magistratura'), ('phd', 'PHD'), ('dsc', 'DSc')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='themesforeducation',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy rahbar'),
        ),
        migrations.AlterField(
            model_name='themesforeducation',
            name='teacher_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy rahbar'),
        ),
        migrations.AlterField(
            model_name='themesforeducation',
            name='teacher_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy rahbar'),
        ),
        migrations.AlterField(
            model_name='themesforeducation',
            name='teacher_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy rahbar'),
        ),
    ]
