# Generated by Django 4.2.5 on 2024-05-27 13:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sectionsboss_delete_bosssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatesThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Malaka oshirish mavzulari',
                'verbose_name_plural': 'Malaka oshirish mavzulari',
                'db_table': 'certificates_themes',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Faqat *.zip, *.docx, *.excel turdagi file yuklang', null=True, upload_to='zip_files/posts/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Faqat *.zip file yuklang', null=True, upload_to='zip_files/posts/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='sectionsandcenters',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Faqat *.pdf formatdagi faylarni yuklang', null=True, upload_to='pdf/sections_and_centers/%Y-%m-%d/', verbose_name='PDF fayl'),
        ),
        migrations.AddField(
            model_name='sectionsandcenters',
            name='pdf_file_en',
            field=models.FileField(blank=True, help_text='Faqat *.pdf formatdagi faylarni yuklang', null=True, upload_to='pdf/en/sections_and_centers/%Y-%m-%d/', verbose_name='EN PDF file'),
        ),
        migrations.AddField(
            model_name='sectionsandcenters',
            name='pdf_file_ru',
            field=models.FileField(blank=True, help_text='Faqat *.pdf formatdagi faylarni yuklang', null=True, upload_to='pdf/ru/sections_and_centers/%Y-%m-%d/', verbose_name='RU PDF file'),
        ),
        migrations.AddField(
            model_name='sectionsandcenters',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Faqat *.zip, *.docx, *.excel turdagi file yuklang', null=True, upload_to='zip_files/posts/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='navbar',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.navbar', verbose_name="Bo'lim nomi"),
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='F.I.SH')),
                ('order', models.FileField(blank=True, null=True, upload_to='pdf/certificates_order/%Y/%m/%d', verbose_name="Sertifikat buyrug'i")),
                ('certificate', models.FileField(blank=True, null=True, upload_to='pdf/certificate/%Y/%m/%d', verbose_name='Sertifikat')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.certificatesthemes', verbose_name='Mavzu')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.year', verbose_name='Malaka oshirish yili')),
            ],
            options={
                'verbose_name': 'Malaka oshirish sertifikatlari',
                'verbose_name_plural': 'Malaka oshirish sertifikatlar',
                'db_table': 'certificates',
                'ordering': ('-add_time',),
            },
        ),
    ]
