# Generated by Django 4.2.5 on 2024-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_certificatesthemes_departments_zip_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionsboss',
            options={'ordering': ('order_num',), 'verbose_name': "Bo'lim raxbarlari", 'verbose_name_plural': "Bo'lim raxbarlari"},
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='phd_special_subject_program',
            field=models.FileField(blank=True, null=True, upload_to='pdf/educational_areas/phd_special_subject_program/%Y/%m/', verbose_name="Mutaxassislik fanlaridan malakaviy va qo'shimcha imtihon dasturlari"),
        ),
        migrations.AddField(
            model_name='educationalareas',
            name='phd_subject_program',
            field=models.FileField(blank=True, null=True, upload_to='pdf/educational_areas/phd_subject_program/%Y/%m/', verbose_name="'Ixtisoslik' fanlari bo'yicha imtihon dasturlari"),
        ),
        migrations.AddField(
            model_name='sectionsboss',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
    ]
