# Generated by Django 4.2.5 on 2024-09-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_sectionsboss_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAdministrationsPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nomi')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nomi')),
                ('order_num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kafedra mamuryati lavozimlari',
                'verbose_name_plural': 'Kafedra mamuryati lavozimlari',
                'db_table': 'department_administrations_positions',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentHeadAdministrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_head_administrations/%Y/%m/%d', verbose_name='Rasm')),
                ('f_name', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('f_name_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('f_name_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('f_name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Pochta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_administration', to='main.departments')),
            ],
            options={
                'verbose_name': 'Kafedra mudirlari',
                'verbose_name_plural': 'Kafedra mudirlari',
                'db_table': 'department_head_administrations',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentAdministrationsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('f_name_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('f_name_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('f_name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name="To'liq ismi")),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-Pochta')),
                ('cv', models.FileField(blank=True, null=True, upload_to='department_administration_cv/%Y/%m/%d', verbose_name='CV File')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_administrations', to='main.departments', verbose_name='Kafedra')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_administrations_positions', to='main.departmentadministrationspositions', verbose_name='Lavozim')),
            ],
            options={
                'verbose_name': 'Kafedra mamuryati (yangi)',
                'verbose_name_plural': 'Kafedra mamuryati (yangi)',
                'db_table': 'department_administrations_new',
                'ordering': ('position',),
            },
        ),
    ]
