# Generated by Django 4.2.5 on 2024-09-25 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_departmentadministrationspositions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityadmistrations',
            name='image',
        ),
        migrations.CreateModel(
            name='UniversityAdministrationsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/administrations/%Y-%m-%d/', verbose_name='Rasmi')),
                ('administration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administration_images', to='main.universityadmistrations')),
            ],
            options={
                'verbose_name': 'Insitut raxbariyati rasmlari',
                'verbose_name_plural': 'Insitut raxbariyati rasmlari',
                'db_table': 'administration_images',
                'ordering': ['administration'],
            },
        ),
    ]
