# Generated by Django 4.2.5 on 2024-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_departmentplandocument_departmentcharterdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevariables',
            name='vacancy',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='basevariables',
            name='vacancy_en',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='basevariables',
            name='vacancy_ru',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='basevariables',
            name='vacancy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basevariables',
            name='vacancy_uz',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
